### ISSUE TITLE
Is it possible to just use the feature flag?

### ISSUE THREAD

**Issue by narcisobenigno** [jnunemaker/flipper-ui#24]
I would like to use the flipper with flipper ui, but it seems to not be ended. Is it possible to start the use of this gems and help you develop this? Would also be possible to just use the feature flag?

best.

**Comment by jeroenvisser101** [comment]
Hi @narcisobenigno, there was #23, which states this is already used in production, and seems to work just fine. I'd suggest you test/use it, and make PRs when you feel something is wrong/broken?

**Comment by narcisobenigno** [comment]
Ok Jeroen,

Thanks!

**Comment by jeroenvisser101** [comment]
You're very welcome :
