### ISSUE TITLE
Add Flipper::API module

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper-ui#29]
Now that we have Flipper::UI it would be nice to have Flipper::API. Flipper::API would provide the same functionality as the UI but all json responses instead of html/css views. Clients could then be created for chatops/hubot to enable/disable features and all that.

**Comment by jeroenvisser101** [comment]
That's pretty damn nice!

**Comment by jnunemaker** [comment]
Moved to https://github.com/jnunemaker/flipper/issues/62
