### ISSUE TITLE
feature_creation_enabled no longer supported?

### ISSUE THREAD

**Issue by tunacasserole** [jnunemaker/flipper-ui#32]
I have this line in my flipper.rb config file:
`Flipper::UI.feature_creation_enabled = false`

It no longer seems supported as I look to upgrade flipper.  Can you point me to the correct way to do this?

**Comment by jnunemaker** [comment]
Flipper::UI.configuration.feature_creation_enabled

**Comment by jnunemaker** [comment]
Settings moved configuration. If that doesn’t help let me know.
